# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0145fdc062e2708c3f45e026af7db2fd4a7724fd3fc0dcdde0405ac783dff73ce3e5bfe8ac9d51f21bba884ec6e771a9f6cc23b48872543b3742d171675573a5

test:
  secret_key_base: c010d6e1a2e47920a9847958a686c9ad911f402f6fa8937ae4fb21c22fd394126d35916f65e54e119be2950854e386a86f48006929d4a193af3030056b72a4ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
